- README.md
- lib/ravelin.rb
- lib/ravelin/chargeback.rb
- lib/ravelin/client.rb
- lib/ravelin/customer.rb
- lib/ravelin/device.rb
- lib/ravelin/errors/api_error.rb
- lib/ravelin/errors/authentication_error.rb
- lib/ravelin/errors/invalid_parameters_error.rb
- lib/ravelin/errors/invalid_request_error.rb
- lib/ravelin/errors/rate_limit_error.rb
- lib/ravelin/event.rb
- lib/ravelin/item.rb
- lib/ravelin/location.rb
- lib/ravelin/order.rb
- lib/ravelin/payment_method.rb
- lib/ravelin/pre_transaction.rb
- lib/ravelin/ravelin_object.rb
- lib/ravelin/response.rb
- lib/ravelin/transaction.rb
- ravelin.gemspec
- spec/ravelin/client_spec.rb
- spec/ravelin/customer_spec.rb
- spec/ravelin/event_spec.rb
- spec/ravelin/order_spec.rb
- spec/ravelin/ravelin_object_spec.rb
- spec/ravelin/response_spec.rb
- spec/spec_helper.rb
The beginnings of a Ruby gem to send events to Ravlin via their web API. Their API docs can be found here - https://developer.ravelin.com/draft
[CW-193](https://deliveroo.atlassian.net/browse/CW-193)
> Add a way to send events to the Ravelin API

- lib/ravelin/ravelin_object.rb
- spec/ravelin/ravelin_object_spec.rb
Ravelin doesn't accept integer values for id parameters identified by their name being suffixed with `_id`.
The code converts those attribute values to strings if they're integers.
> Conversion of integer attributes suffixed with _id to strings

- lib/ravelin/client.rb
- spec/ravelin/client_spec.rb
Ravelin will only return a score for the User when you send `score=true`
as part of the query params. This commit modifies the `send_event` call
to always send this. We want to leave `send_backfill_event` unchanged
however.
[CW-195](https://deliveroo.atlassian.net/browse/CW-195).
> CW-195 Always send score true

- lib/ravelin/ravelin_object.rb
- spec/ravelin/customer_spec.rb
The double splat `**args` only works for keyword args, so this didn't
work for us as we were passing a Hash in. This commit removes the double
splat, so it takes the full Hash as an arguement. And now @samlevy is 😞.
[CW-195](https://deliveroo.atlassian.net/browse/CW-195)
> CW-195 Fix double splat keyword args bug

- README.md
To avoid confusion and to clarify that this isn't a hash with `name`,
`payload` and `timestamp` as keys, this commit changes the `README.md`
to clarify that these are named args.
> Clarify that send_event requires named args

- README.md
- lib/ravelin/client.rb
- spec/ravelin/client_spec.rb
When sending an event to Ravelin, we want to make score optional. This
commit modifies the client to take the `score` arg and use it to add a
query param to the request.
> Make score an optional arg

- lib/ravelin.rb
- lib/ravelin/event.rb
- lib/ravelin/payment_method.rb
- lib/ravelin/ravelin_object.rb
- spec/ravelin/event_spec.rb
- Removes the `/items` endpoint (deprecated)
- Removes the `items` field in the `/order` endpoint (it's now inside the `order` object)
- Allows `customer` as well as the `customer_id` field for endpoints which require a customer
- Ensures `*_id` fields on the root are also converted to strings
CW-186
> Update for Ravelin API changes

- lib/ravelin/event.rb
The `transaction` key should not be required on the `/checkout` endpoint
as there are situations where no card transaction occurs (eg. all-voucher
payment). In this case the transaction field will not exist.
CW-186
> Transaction key not required for checkout

- lib/ravelin/event.rb
Reverts deliveroo/ravelin-ruby#11 as the `transaction` field is actually required!
> Revert "Transaction key not required for checkout"

- lib/ravelin/transaction.rb
In the V2 of the Ravelin API, `transaction_id` is optional.
> Make transaction_id optional

- lib/ravelin/order.rb
This need to be specified when backfilling orders. This commit adds them
to the class.
> Add Creation and Execution time to order

- lib/ravelin.rb
- lib/ravelin/order.rb
- spec/ravelin/order_spec.rb
- spec/ravelin/ravelin_object_spec.rb
Adds the missing `status` field to orders.
Branches off #16.
Jira story [#CW-754](https://deliveroo.atlassian.net/browse/CW-754).
> CW-754: Add order status to Ravelin

- ravelin.gemspec
This commit removes the conditional check blocking publishing to
Rubygems.
> Allow publishing to rubygems

- lib/ravelin/pre_transaction.rb
- lib/ravelin/transaction.rb
`type` and `time` are valid pretransition attributes as can be seen on [Ravelin API docs](https://developer.ravelin.com/#post-/v2/pretransaction)
> Add missing fields to Pretransaction Object

- lib/ravelin/event.rb
Ravelin API docs state the field is optional :
https://developer.ravelin.com/\#post-/v2/login
> Remove temp_customer_id as a required field from login

- lib/ravelin.rb
- lib/ravelin/event.rb
- lib/ravelin/transaction.rb
- lib/ravelin/version.rb
- spec/ravelin/event_spec.rb
Updated to support `3ds`.
Unfortunately we had to do it a bit hacky because ruby wouldn't support `3ds` as an attribute.
===
Jira story [#PAY-1162](https://deliveroo.atlassian.net/browse/PAY-1162) in project *Payments*:
> ## Why?
> 
> We need to support https://developer.ravelin.com/v2/#3d-secure in the ravelin gem: https://github.com/deliveroo/ravelin-ruby.
> 
> ## What?
> 
> Add functionality, increment version and push to remote gem repos.
> 
> ## Test?
> 
> Will be covered by https://deliveroo.atlassian.net/browse/PAY-539
> PAY-1162: Update Ravelin gem to support 3DS

- lib/ravelin.rb
- lib/ravelin/three_d_secure.rb
- lib/ravelin/transaction.rb
- lib/ravelin/version.rb
- spec/ravelin/event_spec.rb
- spec/ravelin/three_d_secure_spec.rb
We were still sending 3DS data in `snake_case` and needed to send in `camelCase` (see: https://developer.ravelin.com/v2/#3d-secure).
===
Jira story [#PAY-1162](https://deliveroo.atlassian.net/browse/PAY-1162) in project *Payments*:
> ## Why?
> 
> We need to support https://developer.ravelin.com/v2/#3d-secure in the ravelin gem: https://github.com/deliveroo/ravelin-ruby.
> 
> ## What?
> 
> Add functionality, increment version and push to remote gem repos.
> 
> ## Test?
> 
> Will be covered by https://deliveroo.atlassian.net/browse/PAY-539
> PAY-1162: camelize 3DS payload data

- lib/ravelin/three_d_secure.rb
- spec/ravelin/three_d_secure_spec.rb
If we send `nil` or an integer less that `100` (e.g. `nil.to_i => 0`) for the 3DS start or end times we will break the JSON schema contract. This PR adds some safety to the client, though we still need to be more circumspect with the data we pass when sending events.
> Ensure 3DS events adhere to schema

- lib/ravelin/client.rb
- spec/ravelin/client_spec.rb
Adding support for Ravelin's GET tags endpoint. Also fleshing out specs. 
NB: the endpoint is `/v2/tag/customer?customerId=[id]` on the docs but I've confirmed that it's deprecated and that the new format is `/v2/tag/customer/[id]`
> Add get tags

- CHANGELOG.md
- lib/ravelin/event.rb
- lib/ravelin/version.rb
- spec/ravelin/event_spec.rb
ATO Reclaim Events:
* Corrects formatting for timestamps in `serializable_hash`
ATO Login Events:
* Uses a standardised unix timestamp during creation
* Default timestamp will now be correct
* Adds validation to required fields
> AI-12: Add correct formatting of ato reclaim event timestamps

- CHANGELOG.md
- lib/ravelin/version.rb
- ravelin.gemspec
* downgraded faraday dependency versions due to orderweb conflicts
* switched rspec back to it's original version that was before the PRC-101 work.
After importing the gem into orderweb, there were faraday dependency issues due to bumping the versions. Really, we only need `webmock` updated.
> PRC-101: fix dependencies

- CHANGELOG.md
- lib/ravelin/response.rb
- lib/ravelin/version.rb
- spec/ravelin/response_spec.rb
Update the response in the Ravelin gem to include the warnings as a structured `warnings` field.
We are going to push metrics when we receive warnings from Ravelin. After coding this in orderweb, I realised that we should update the Ravelin gem instead of doing this based off the body that is returned.
> PRC-107: return warnings from Ravelin

- lib/ravelin/event.rb
The API documentation for the all in one Ravelin checkout API (https://developer.ravelin.com/apis/v2/#postv2checkout) lists the fields are `important` rather than `required`:
- customer
- order
- payment_method
- transaction
This PR removes usage of `validate_payload_inclusion_of` to match the spec.
> Update required fields for all in one checkout API

- lib/ravelin/checkout_transaction.rb
- lib/ravelin/pre_transaction.rb
- lib/ravelin/version.rb
Gateway is not required pre transaction as it is not always know. As the Ravelin docs say "Usually only available after attempting the payment."
> Trust 603: remove gateway as required

- CHANGELOG.md
- lib/ravelin/login.rb
- lib/ravelin/version.rb
- spec/ravelin/login_spec.rb
In order to be able to connect the request from `orderweb` with the notification or decision taken by Ravelin, we need to send the generated `decision_id` when calling Ravelin's API.
The `Ravelin::Login` object currently doesn't support the `custom` property that the API supports.
This PR solves just that, by adding the optional field to the object.
> [TRUST-758] Add custom property on login

- CHANGELOG.md
- lib/ravelin.rb
- lib/ravelin/authentication_mechanism.rb
- lib/ravelin/authentication_mechanisms/social.rb
- lib/ravelin/version.rb
- spec/ravelin/authentication_mechanisms/social_spec.rb
This PR adds support for the social login authentication mechanism. 
More info about the API signature can be found here: https://developer.ravelin.com/apis/ato/#login.login.authenticationMechanism.social
> [TRUST-351] Add support for social login authentication mechanism

- CHANGELOG.md
- lib/ravelin/authentication_mechanism.rb
- lib/ravelin/event.rb
- lib/ravelin/version.rb
- spec/ravelin/authentication_mechanism_spec.rb
- spec/ravelin/event_spec.rb
The implementation of the `Ravelin::AuthenticationMechanisms::Social` object was incorrect, and the way that the tests were created did not detect the error.
This PR addresses that bug, as well as correctly creating the full login object tree when it is initialised with an hash containing the social authentication mechanism.
> Fix Ravelin::AuthenticationMechanisms::Social object creation

- CHANGELOG.md
- lib/ravelin.rb
- lib/ravelin/authentication_mechanism.rb
- lib/ravelin/authentication_mechanisms/sms_code.rb
- lib/ravelin/event.rb
- lib/ravelin/version.rb
- spec/ravelin/authentication_mechanism_spec.rb
- spec/ravelin/authentication_mechanisms/sms_code_spec.rb
This PR adds the object that is required to signal a SMS code login.
Some fixes to the changelog are also included
> Add SmsCode authentication mechanism to ATO login request

- .github/workflows/codeql-analysis.yml
Artifact storage has hit its limit. We need to turn debug mode off for codeql scanning to avoid running up a bill. 
[PSC-662](https://deliveroo.atlassian.net/browse/PSC-662)
[PSC-662]: https://deliveroo.atlassian.net/browse/PSC-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> removing debug step to reduce artifacts retained

- CHANGELOG.md
- lib/ravelin/client.rb
- lib/ravelin/version.rb
- ravelin.gemspec
- spec/ravelin/client_spec.rb
- spec/ravelin/proxy_client_spec.rb
This PR with release VERSION = '0.1.47': 
- Adds functionality to Ravelin client to accept extra headers for a request. 
Why: 
The current need for this is to send Comparator-Request-Id header from Orderweb to Cluedo (Ravelin Proxy).
> TRST-1837: Ravelin client to handle extra headers for post request
