deliveroo/ravelin-ruby

lib/ravelin.rb
lib/ravelin/event.rb
lib/ravelin/ravelin_object.rb
spec/ravelin/event_spec.rb
spec/ravelin/ravelin_object_spec.rb

Add Ruby time conversion to epoch integers for payload parameters that accept times

Accept Time object parameters and convert to epoch

---

lib/ravelin.rb
spec/ravelin/ravelin_object_spec.rb

This fixes date/time conversions when the timezone isn't UTC.

Fix time conversions

---

lib/ravelin/transaction.rb

Reverts deliveroo/ravelin-ruby#13

Revert "Make transaction_id optional"

---

lib/ravelin/customer.rb

* Correct `username`
* Add `market`

Correction to Customer fields

---

lib/ravelin.rb
lib/ravelin/event.rb
lib/ravelin/voucher.rb
spec/ravelin/voucher_spec.rb

[#MKT-336](https://deliveroo.atlassian.net/browse/MKT-336)

Add voucher to API for MKT-336;

---

README.md
lib/ravelin/version.rb
ravelin.gemspec
spec/ravelin/voucher_spec.rb

- Add initial draft voucher docs - to be finalised when ravelin releases voucher API;
- Add Mathilda Thompson as author;
- Bump up version number for release;

Add initial voucher docs;

---

lib/ravelin/version.rb

- update gem version number for voucher_redemption object release;

update gem version number

---

lib/ravelin/event.rb

[MKT-367](https://deliveroo.atlassian.net/browse/MKT-367)

Add payload validation for voucher_redemption;

---

CHANGELOG.md
ChangeLog.md

Rename ChangeLog.md to CHANGELOG.md

---

lib/ravelin/device.rb

Can be seen under device on Ravelin API docs
https://developer.ravelin.com/#post-/v2/login

Add user_agent to device RavelinObject

---

lib/ravelin/event.rb
spec/ravelin/event_spec.rb

For the 'transaction' and 'pretransaction' events these two fields are mutually exclusive. See:
https://developer.ravelin.com/v2/#postv2transaction
https://developer.ravelin.com/v2/#postv2pretransaction

Fix validation to not require payment_method_id if payment_method provided

---

lib/ravelin/payment_method.rb

See docs: https://developer.ravelin.com/v2/

Include new ewallet field

---

lib/ravelin/client.rb
spec/ravelin/client_spec.rb

Adding support for deleting customer tags.

Add delete tags

---

lib/ravelin/response.rb
spec/ravelin/response_spec.rb

Adding support for tag responses

Adding support for tag responses

---

lib/ravelin/response.rb
spec/ravelin/response_spec.rb

The tag response isn't nested within a `data` key

Fixed the data structure of the tag response

---

lib/ravelin/client.rb
lib/ravelin/response.rb
spec/ravelin/client_spec.rb
spec/ravelin/response_spec.rb
spec/ravelin/tag_spec.rb

Fixing bugs with the delete tags methods and the response for the tag endpoints

Fixed bugs in client file and responses

---

lib/ravelin/client.rb
spec/ravelin/client_spec.rb

Delete tag requests url fix

---

CHANGELOG.md
lib/ravelin/version.rb

AI-XXx: Update version

---

CHANGELOG.md
lib/ravelin/event.rb
lib/ravelin/version.rb
spec/ravelin/event_spec.rb

Disambiguate between V2 and V3 login events - applying correct validation and timestamp formatting

AI-12: Fix login event clashes

---

.github/CODEOWNERS
README.md

Add ownership to readme and add a CODEOWNERS file

TRUST-XXX: ownership

---

.travis.yml
README.md

Removes the old travis config and update the README.

TRUST-606: Finalise move to circleci

---

lib/ravelin/checkout_transaction.rb

Applies the same renaming we do in a normal transaction

TRUST-XXX: Apply 3ds rename to checkout transaction

---

CHANGELOG.md
lib/ravelin/payment_method.rb
lib/ravelin/version.rb

Add optional 'scheme' to the paymentMethod key for cash payments
API reference
https://developer.ravelin.com/apis/v2/#checkout.paymentMethod.0.scheme

TRUST-XXX: Add scheme to paymentMethod key

---

lib/ravelin/order.rb

Adds the category field to order
See https://api.ravelin.com/v2/checkout/schema.json

TRUST-858: Add category field to order

---

CHANGELOG.md
lib/ravelin/version.rb

TRUST-858: Bump version and update changelog

---

CHANGELOG.md
lib/ravelin/order.rb
lib/ravelin/version.rb

Add missing comma to make categories work
Bump version and update changelog as well.

TRUST-858: Fix order category

---

lib/ravelin/event.rb
spec/ravelin/event_spec.rb

Serialize multiple transactions under the `transactions` key.

Serialize transactions

---

.github/workflows/codeql-analysis.yml

Codeql cron string updated to twice a month, 45 minute timeout and debugging enabled

PSC-610,PSC-611 - codeql improvements
